version: '3'
services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_NAME=moviesdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=movies
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data:
